name: Daily Updates

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight UTC
  release:
    types: [published] # Also trigger on new releases
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      # Update language distribution
      - name: Update language distribution
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python scripts/update_language_stats.py
      
      - name: Check for language changes
        id: check_lang_changes
        run: |
          if [[ -n $(git diff --name-only README.md) ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi
      
      # Update blog posts
      - name: Update blog posts
        run: python scripts/update_blog_posts.py
      
      - name: Check for blog changes
        id: check_blog_changes
        run: |
          if [ -f blog_changes_detected ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
            rm blog_changes_detected
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi
      
      # Update recent releases
      - name: Fetch Recent Releases
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            
            // Function to extract release data from HTML section
            function extractReleaseData(section) {
              console.log('Raw section:', section); // Debug log
              
              const releases = [];
              // Extract lines from the <pre> tag
              const preMatch = section.match(/<pre[^>]*>([\s\S]*?)<\/pre>/);
              if (!preMatch) return releases;
              
              const lines = preMatch[1].split('\n').filter(line => line.trim());
              console.log(`Found ${lines.length} lines`); // Debug log
              
              for (const line of lines) {
                console.log('Processing line:', line); // Debug log
                
                // Parse compact format: <a href="...">RepoName</a> v1.0.0 [Lang] ⭐N • Description
                const repoMatch = line.match(/href="[^"]+">([^<]+)<\/a>/);
                const versionMatch = line.match(/<\/a>\s+([^\s]+)\s+\[/);
                const starsMatch = line.match(/⭐(\d+)/);
                
                console.log('Extracted line data:', { // Debug log
                  repo: repoMatch?.[1],
                  version: versionMatch?.[1],
                  stars: starsMatch?.[1]
                });
                
                if (repoMatch && versionMatch) {
                  releases.push({
                    repo: repoMatch[1],
                    version: versionMatch[1],
                    stars: starsMatch ? parseInt(starsMatch[1]) : 0
                  });
                }
              }
              
              console.log('Final extracted releases:', releases); // Debug log
              return releases;
            }

            // Function to compare two release arrays with detailed logging
            function releasesAreDifferent(oldReleases, newReleases) {
              console.log('\nComparing releases:');
              console.log('Old releases:', JSON.stringify(oldReleases, null, 2));
              console.log('New releases:', JSON.stringify(newReleases, null, 2));
              
              if (oldReleases.length !== newReleases.length) {
                console.log(`Length mismatch: old=${oldReleases.length}, new=${newReleases.length}`);
                return true;
              }
              
              for (let i = 0; i < oldReleases.length; i++) {
                const old = oldReleases[i];
                const newR = newReleases[i];
                
                console.log(`\nComparing release ${i + 1}:`);
                console.log('Old:', old);
                console.log('New:', newR);
                
                if (old.repo !== newR.repo) {
                  console.log(`Repository changed: ${old.repo} -> ${newR.repo}`);
                  return true;
                }
                if (old.version !== newR.version) {
                  console.log(`Version changed for ${old.repo}: ${old.version} -> ${newR.version}`);
                  return true;
                }
                // Skip date comparison in compact format
                if (old.stars !== newR.stars) {
                  console.log(`Stars changed for ${old.repo}: ${old.stars} -> ${newR.stars}`);
                  return true;
                }
                
                console.log(`No changes detected for ${old.repo}`);
              }
              
              console.log('\nNo differences found between releases');
              return false;
            }
            
            // Read current README first
            console.log('Reading README...');
            let readme = fs.readFileSync('README.md', 'utf8');
            
            // Extract current releases section if it exists
            let originalSection = '';
            let currentReleases = [];
            if (readme.includes('<!-- Recent Releases -->')) {
              console.log('Found existing releases section');
              const start = readme.indexOf('<!-- Recent Releases -->');
              const end = readme.indexOf('<!-- End Recent Releases -->') + '<!-- End Recent Releases -->'.length;
              originalSection = readme.substring(start, end);
              currentReleases = extractReleaseData(originalSection);
              console.log('Extracted current releases:', currentReleases);
            } else {
              console.log('No existing releases section found');
            }
            
            console.log('Fetching repositories...');
            const repos = await github.rest.repos.listForUser({
              username: context.repo.owner,
              per_page: 100,
              sort: 'updated'
            });
            
            // Create a map to store latest release per repo
            let repoReleasesMap = new Map();
            
            // Fetch releases and additional repo data
            console.log(`\nFetching release data for ${repos.data.length} repositories...`);
            for (const repo of repos.data) {
              try {
                console.log(`\nProcessing ${repo.name}...`);
                const [releases, repoDetails] = await Promise.all([
                  github.rest.repos.listReleases({
                    owner: context.repo.owner,
                    repo: repo.name,
                    per_page: 1
                  }),
                  github.rest.repos.get({
                    owner: context.repo.owner,
                    repo: repo.name
                  })
                ]);
                
                if (releases.data.length > 0) {
                  const release = releases.data[0];
                  release.repo_name = repo.name;
                  release.language = repo.language;
                  release.stars = repoDetails.data.stargazers_count;
                  release.description = repoDetails.data.description;
                  repoReleasesMap.set(repo.name, release);
                  console.log(`Found release: ${release.name || release.tag_name}`);
                } else {
                  console.log('No releases found');
                }
              } catch (error) {
                console.log(`Error fetching data for ${repo.name}: ${error.message}`);
              }
            }
            
            // Convert map to array and sort by date
            let allReleases = Array.from(repoReleasesMap.values());
            allReleases.sort((a, b) => new Date(b.published_at) - new Date(a.published_at));
            allReleases = allReleases.slice(0, 20);
            console.log(`\nProcessed ${allReleases.length} most recent releases`);
            
            function formatDate(dateStr) {
              const date = new Date(dateStr);
              return date.toLocaleDateString('en-US', {
                month: 'short',
                day: 'numeric',
                year: 'numeric'
              });
            }
            
            // Prepare new section
            let newSection;
            let newReleasesData = [];
            
            if (allReleases.length === 0) {
              console.log('No releases found, creating empty section');
              newSection = [
                '\n<!-- Recent Releases -->',
                '<div style="width: 80%; text-align: right;">',
                '<h3>📦 Latest Releases</h3>',
                '<p>No releases yet</p>',
                '</div>',
                '<!-- End Recent Releases -->'
              ].join('\n');
            } else {
              // Transform the new releases into comparable format
              newReleasesData = allReleases.map(release => ({
                repo: release.repo_name,
                version: release.name || release.tag_name,
                stars: release.stars
              }));
              
              console.log('\nPreparing new releases data:', newReleasesData);
              
              // Shorten language names
              function shortLang(lang) {
                const langMap = {
                  'Swift': 'Swift',
                  'Go': 'Go',
                  'JavaScript': 'JS',
                  'TypeScript': 'TS',
                  'Python': 'Py',
                  'Rust': 'Rust',
                  'Java': 'Java',
                  'C++': 'C++',
                  'C': 'C',
                  'Ruby': 'Ruby',
                  'PHP': 'PHP',
                  'Kotlin': 'Kotlin',
                  'Dart': 'Dart',
                  'Lua': 'Lua'
                };
                return langMap[lang] || lang || 'N/A';
              }
              
              // Just return the description as-is
              function getDesc(desc) {
                return desc || '';
              }
              
              const releaseLines = allReleases.map(release => {
                const name = release.name || release.tag_name;
                const lang = shortLang(release.language);
                const desc = getDesc(release.description);
                const stars = release.stars.toString();
                return `<a href="${release.html_url}">${release.repo_name}</a> ${name} [${lang}] ⭐${stars}${desc ? ' • ' + desc : ''}`;
              }).join('\n');

              newSection = [
                '\n<!-- Recent Releases -->',
                '<div style="width: 80%; text-align: right;">',
                '<h3>📦 Latest Releases</h3>',
                '<pre style="text-align: left; margin-left: auto; font-size: 0.7em; line-height: 1.4;">',
                releaseLines,
                '</pre>',
                '</div>',
                '<!-- End Recent Releases -->\n'
              ].join('\n');
            }
            
            // Compare the actual release data instead of HTML content
            if (releasesAreDifferent(currentReleases, newReleasesData)) {
              console.log('\nChanges detected in release data, updating README...');
              // Update or append the section
              if (originalSection) {
                readme = readme.replace(originalSection, newSection);
                console.log('Updated existing section');
              } else {
                const insertPoint = readme.indexOf('![Profile views]');
                if (insertPoint !== -1) {
                  readme = readme.slice(0, insertPoint) + newSection + readme.slice(insertPoint);
                  console.log('Inserted new section before profile views');
                } else {
                  readme += newSection;
                  console.log('Appended new section at end of README');
                }
              }
              
              fs.writeFileSync('README.md', readme);
              fs.writeFileSync('releases_changes_detected', 'true');
            } else {
              console.log('\nNo changes detected in release data, skipping update');
            }
      
      - name: Check for releases changes
        id: check_releases_changes
        run: |
          if [ -f releases_changes_detected ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
            rm releases_changes_detected
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi
      
      # Commit changes if any
      - name: Commit and push if changed
        if: steps.check_lang_changes.outputs.changes == 'true' || steps.check_blog_changes.outputs.changes == 'true' || steps.check_releases_changes.outputs.changes == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md
          
          # Determine commit message based on what changed
          changes=()
          [[ "${{ steps.check_lang_changes.outputs.changes }}" == "true" ]] && changes+=("language distribution")
          [[ "${{ steps.check_blog_changes.outputs.changes }}" == "true" ]] && changes+=("blog posts")
          [[ "${{ steps.check_releases_changes.outputs.changes }}" == "true" ]] && changes+=("recent releases")
          
          # Join array elements with commas and 'and' for the last element
          message="Update "
          if [ ${#changes[@]} -eq 1 ]; then
            message+="${changes[0]}"
          elif [ ${#changes[@]} -eq 2 ]; then
            message+="${changes[0]} and ${changes[1]}"
          elif [ ${#changes[@]} -eq 3 ]; then
            message+="${changes[0]}, ${changes[1]} and ${changes[2]}"
          fi
          message+=" [skip ci]"
          
          git commit -m "$message"
          git push